### ISSUE TITLE
Sometimes it throws error that google play service is missing

### ISSUE THREAD

**Issue by bivekvivek** [CodesFirst/safetynet_attestation#2]
It throws an error that google play services is missing even though google play services  is available 
It would be better if there was no checking for GMS availability before running 
      SafetynetAttestation().safetyNetAttestationPayload('nonce');

Tested on Android 12L

**Comment by pewiher** [comment]
Hello good afternoon, how are you, the respective tests were carried out and they were satisfactory, with respect to removing the verification of the google service, it is not feasible since it is mandatory and recommended by google, this is for the correct functioning of SafetyNet Attestation API.

Possibly the event is occurring because the SafetyNet API Key is not configured in the manifest, for this you must generate a credential in your google cloud account, and add it to the manifest.

In this section

`<!-- Replace with your SafetyNet Attestation API Key -->`
`       <meta-data android:name="safetynet_api_key"`
`           android:value="you_api_key"/>`

For more information read the following article: [safetynet](https://developer.android.com/training/safetynet/attestation).

If the safetynet key has been configured and the event still occurs, you could provide us with the log for a better analysis of it.

I remain attentive to comments and suggestions.

**Comment by bivekvivek** [comment]
Hello, Good morning sir 

I have configured the API properly and even using it in production..

To be exact the issue occured on some vanilla custom roms on which minimal gapps is flashed.. and also some custom MIUI roms.Where as some natively built Safetynet test app worked fine..

I have built this app using your plugin 
(safetynet_attestation 0.0.5)
https://play.google.com/store/apps/details?id=com.safetynet.bivek

Thank you so much for your work!

**Comment by pewiher** [comment]
> Hello, Good morning sir
> 
> I have configured the API properly and even using it in production..
> 
> To be exact the issue occured on some vanilla custom roms on which minimal gapps is flashed.. and also some custom MIUI roms.Where as some natively built Safetynet test app worked fine..
> 
> I have built this app using your plugin (safetynet_attestation 0.0.5) https://play.google.com/store/apps/details?id=com.safetynet.bivek
> 
> Thank you so much for your work!

I am glad that it has been of use to you, the test has not been carried out on devices with modified rooms, some of them do not have important characteristics for android devices, for this it is recommended to first verify if the google service is available on the device, it could use the call to checkGooglePlayServicesAvailability, available in the packet, any news do not hesitate to write to us.

have a nice day :)
